[package]
name = "nexus-client"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Client daemon, auto mode controller, and multi-WAN bonding engine"

[dependencies]
nexus-proto = { path = "../nexus-proto" }
nexus-crypto = { path = "../nexus-crypto" }
nexus-linkmon = { path = "../nexus-linkmon" }
nexus-sched = { path = "../nexus-sched" }
nexus-tun = { path = "../nexus-tun" }
nexus-ipc = { path = "../nexus-ipc" }
tokio.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
toml.workspace = true
